import Head from "next/head";
import Body from "../components/Body";
import Footer from "../components/Footer";
import Header from "../components/Header";
import useLoading from "../hooks/useLoading";
import Loading from "../components/Loading";

export default function Home() {
  const {loading} = useLoading();
  return (
    <div>
      <Head>
        <title>Google</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {loading ? (<Loading/>) : null}
      <Header />
      <Body />
      <Footer />
    </div>
  );
}
