import Head from "next/head";
import SearchHeader from "../components/SearchHeader";

function search() {
  return (
    <div>
      <Head>
        <title>Google - Search</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SearchHeader />
    </div>
  );
}

export default search;
