import Head from "next/head";
import SearchHeader from "../components/SearchHeader";
import Response from "../Response";

function search({ results }) {
  console.log(results);
  return (
    <div>
      <Head>
        <title>Google - Search</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SearchHeader />
    </div>
  );
}

export default search;

export async function getServerSideProps(context) {
  const mockData = true;
  const { term, searchType } = context.query;
  const data = mockData
    ? Response
    : await fetch(
        `https://www.googleapis.com/customsearch/v1?key=${
          process.env.API_KEY
        }&cx=${process.env.CONTEXT_KEY}&q=${term}${
          searchType && "&searchType=image"
        }`
      ).then((response) => response.json());
  return {
    props: {
      results: data,
    },
  };
}
